---
title: Afbeeldingen verplaatsen
hero_image: images/banner.png
description: bewerking-verplaatsing beschrijving
version: 4
listed: false
copyedit: false
last_tested: "2021-08-05"
steps:
  - title: Inleiding
