---
title: Trosi elfennau gweledol
hero_image: images/banner.png
description: processing-translation description
version: 4
listed: false
copyedit: false
last_tested: "2021-08-05"
steps:
  - 
    title: Cyflwyniad
