---
title: Deslocar elementos visuais
hero_image: images/banner.png
description: descrição de processamento de translação
version: 4
listed: false
copyedit: false
last_tested: "2021-08-05"
steps:
  - 
    title: Introdução
