---
title: Trasladando imágenes
hero_image: images/banner.png
description: descripción de procesamiento-traslado
version: 4
listed: false
copyedit: false
last_tested: "2021-08-05"
steps:
  - 
    title: Introducción
