---
title: Translater des images
hero_image: images/banner.png
description: traitement-translation description
version: 4
listed: false
copyedit: false
last_tested: "2021-08-05"
steps:
  - title: Introduction
